services:
  sutureformer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/workspace
      - /path/to/dataset:/path/to/dataset
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    shm_size: "16g"
    command:
      - "train.py"
